/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.graphics.drawable;

public final class R {
    public static final class attr {
        public static final int font = 0x7f0400a4;
        public static final int fontProviderAuthority = 0x7f0400a6;
        public static final int fontProviderCerts = 0x7f0400a7;
        public static final int fontProviderFetchStrategy = 0x7f0400a8;
        public static final int fontProviderFetchTimeout = 0x7f0400a9;
        public static final int fontProviderPackage = 0x7f0400aa;
        public static final int fontProviderQuery = 0x7f0400ab;
        public static final int fontStyle = 0x7f0400ac;
        public static final int fontWeight = 0x7f0400ad;
    }
    public static final class bool {
        public static final int abc_action_bar_embed_tabs = 0x7f050000;
    }
    public static final class color {
        public static final int notification_action_color_filter = 0x7f060053;
        public static final int notification_icon_bg_color = 0x7f060054;
        public static final int ripple_material_light = 0x7f06005f;
        public static final int secondary_text_default_material_light = 0x7f060061;
    }
    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 0x7f07005b;
        public static final int compat_button_inset_vertical_material = 0x7f07005c;
        public static final int compat_button_padding_horizontal_material = 0x7f07005d;
        public static final int compat_button_padding_vertical_material = 0x7f07005e;
        public static final int compat_control_corner_material = 0x7f07005f;
        public static final int notification_action_icon_size = 0x7f07009f;
        public static final int notification_action_text_size = 0x7f0700a0;
        public static final int notification_big_circle_margin = 0x7f0700a1;
        public static final int notification_content_margin_start = 0x7f0700a2;
        public static final int notification_large_icon_height = 0x7f0700a3;
        public static final int notification_large_icon_width = 0x7f0700a4;
        public static final int notification_main_column_padding_top = 0x7f0700a5;
        public static final int notification_media_narrow_margin = 0x7f0700a6;
        public static final int notification_right_icon_size = 0x7f0700a7;
        public static final int notification_right_side_padding_top = 0x7f0700a8;
        public static final int notification_small_icon_background_padding = 0x7f0700a9;
        public static final int notification_small_icon_size_as_large = 0x7f0700aa;
        public static final int notification_subtext_size = 0x7f0700ab;
        public static final int notification_top_pad = 0x7f0700ac;
        public static final int notification_top_pad_large_text = 0x7f0700ad;
    }
    public static final class drawable {
        public static final int notification_action_background = 0x7f080076;
        public static final int notification_bg = 0x7f080077;
        public static final int notification_bg_low = 0x7f080078;
        public static final int notification_bg_low_normal = 0x7f080079;
        public static final int notification_bg_low_pressed = 0x7f08007a;
        public static final int notification_bg_normal = 0x7f08007b;
        public static final int notification_bg_normal_pressed = 0x7f08007c;
        public static final int notification_icon_background = 0x7f08007d;
        public static final int notification_template_icon_bg = 0x7f08007e;
        public static final int notification_template_icon_low_bg = 0x7f08007f;
        public static final int notification_tile_bg = 0x7f080080;
        public static final int notify_panel_notification_icon_bg = 0x7f080081;
    }
    public static final class id {
        public static final int action_container = 0x7f0a000f;
        public static final int action_divider = 0x7f0a0011;
        public static final int action_image = 0x7f0a0012;
        public static final int action_text = 0x7f0a0018;
        public static final int actions = 0x7f0a0019;
        public static final int async = 0x7f0a001f;
        public static final int blocking = 0x7f0a0024;
        public static final int chronometer = 0x7f0a0031;
        public static final int forever = 0x7f0a0053;
        public static final int icon = 0x7f0a005f;
        public static final int icon_group = 0x7f0a0060;
        public static final int info = 0x7f0a0066;
        public static final int italic = 0x7f0a0068;
        public static final int line1 = 0x7f0a006d;
        public static final int line3 = 0x7f0a006e;
        public static final int normal = 0x7f0a0088;
        public static final int notification_background = 0x7f0a0089;
        public 