/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.coreutils;

public final class R {
    public static final class attr {
        public static final int font = 0x7f0400a4;
        public static final int fontProviderAuthority = 0x7f0400a6;
        public static final int fontProviderCerts = 0x7f0400a7;
        public static final int fontProviderFetchStrategy = 0x7f0400a8;
        public static final int fontProviderFetchTimeout = 0x7f0400a9;
        public static final int fontProviderPackage = 0x7f0400aa;
        public static final int fontProviderQuery = 0x7f0400ab;
        public static final int fontStyle = 0x7f0400ac;
        public static final int fontWeight = 0x7f0400ad;
    }
    public static final class bool {
        public static final int abc_action_bar_embed_tabs = 0x7f050000;
    }
    public static final class color {
        public static final int notification_action_color_filter = 0x7f060053;
        public static final int notification_icon_bg_color = 0x7f060054;
        public static final int ripple_material_light = 0x7f06005f;
        public static final int secondary_text_default_material_light = 0x7f060061;
    }
    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 0x7f07005b;
        public static final int compat_button_inset_vertical_material = 0x7f07005c;
        public static final int compat_button_padding_horizontal_material = 0x7f07005d;
        public static final int compat_button_padding_vertical_material = 0x7f07005e;
        public static final int compat_control_corner_material = 0x7f07005f;
        public static final int notification_action_icon_size = 0x7f07009f;
        public static final int notification_action_text_size = 0x7f0700a0;
        public static final int notification_big_circle_margin = 0x7f0700a1;
        public static final int notification_content_margin_start = 0x7f0700a2;
        public static final int notification_large_icon_height = 0x7f0700a3;
        public static final int notification_large_icon_width = 0x7f0700a4;
        public static final int notification_main_column_padding_top = 0x7f0700a5;
        public static final int notifica